### ISSUE TITLE
The Race to v1

### ISSUE THREAD

**Issue by dylmye** [dylmye/pelleglobe#1]
- [x] Implement React (#2)
- [x] Implement Google Map (#3)
- [ ] Airtable: Address -> Long&Lat (#4)
- [ ] Airtable Long&Lat -> Markers (#5)
- [ ] Airtable Drinks grid & modal (#6)

Comment with extra things that would be nice, maybe for a second milestone
